title: Roo Documentation
description: Documentation for the Roo project
remote_theme: just-the-docs/just-the-docs

url: https://shanemmattner.github.io/roo-code

aux_links:
  "Roo on GitHub":
    - "//github.com/shanemmattner/roo-code"

# Enable search
search_enabled: true

# Enable dark mode
color_scheme: dark