name: Update Contributors

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update contributors
        run: npm run update-contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to README.md"
          fi
          
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update contributors list"
          title: "Update contributors list"
          body: |
            Automated update of contributors list in README.md
            
            This PR was created automatically by a GitHub Action workflow.
          branch: update-contributors
          branch-suffix: timestamp
          delete-branch: true
          base: main